use crate::model::{AppInfo, AppMetric, AppRating, FullAppInfo};
use chrono::Local;
use sqlx::{FromRow, Row, postgres::PgRow};

use crate::db::Database;

pub const SELECT_APP_INFO_FIELDS: &str = r#"
    app_id, alliance_app_id, name, pkg_name,
    dev_id, developer_name, dev_en_name,
    supplier, kind_id, kind_name,
    tag_name, kind_type_id, kind_type_name, icon_url,
    brief_desc, description, privacy_url, ctype,
    detail_id, app_level, jocat_id, iap, hms,
    tariff_type, packing_type, order_app, denpend_gms,
    denpend_hms, force_update, img_tag, is_pay,
    is_disciplined, is_shelves, submit_type, delete_archive,
    charging, button_grey, app_gift, free_days,
    pay_install_type, created_at, listed_at, comment,
    release_countries, main_device_codes,
    version, version_code, size_bytes, sha256, info_score,
    info_rate_count, download_count, price, release_date,
    new_features, upgrade_msg, target_sdk, minsdk, compile_sdk_version,
    min_hmos_api_level, api_release_type, metrics_created_at,
    average_rating, star_1_rating_count, star_2_rating_count,
    star_3_rating_count, star_4_rating_count, star_5_rating_count,
    my_star_rating, total_star_rating_count, only_star_count,
    full_average_rating, source_type, rating_created_at
"#;

pub const SELECT_APP_METRIC_FIELDS: &str = r#"
    app_id, version, version_code, size_bytes,
    sha256, info_score, info_rate_count,
    download_count, price, release_date,
    new_features, upgrade_msg, target_sdk,
    minsdk, compile_sdk_version, min_hmos_api_level,
    api_release_type, created_at AS metrics_created_at
"#;

pub const SELECT_APP_RATING_FIELDS: &str = r#"
    id, app_id, pkg_name, average_rating, star_1_rating_count,
    star_2_rating_count, star_3_rating_count,
    star_4_rating_count, star_5_rating_count,
    my_star_rating, total_star_rating_count,
    only_star_count, full_average_rating,
    source_type, created_at AS rating_created_at
"#;

impl Database {
    pub fn read_app_info_from_row(row: &PgRow) -> AppInfo {
        AppInfo {
            app_id: row.get("app_id"),
            alliance_app_id: row.get("alliance_app_id"),
            name: row.get("name"),
            pkg_name: row.get("pkg_name"),
            dev_id: row.get("dev_id"),
            developer_name: row.get("developer_name"),
            dev_en_name: row.get("dev_en_name"),
            supplier: row.get("supplier"),
            kind_id: row.get("kind_id"),
            kind_name: row.get("kind_name"),
            tag_name: row.get("tag_name"),
            kind_type_id: row.get("kind_type_id"),
            kind_type_name: row.get("kind_type_name"),
            icon_url: row.get("icon_url"),
            brief_desc: row.get("brief_desc"),
            description: row.get("description"),
            privacy_url: row.get("privacy_url"),
            ctype: row.get("ctype"),
            detail_id: row.get("detail_id"),
            app_level: row.get("app_level"),
            jocat_id: row.get("jocat_id"),
            iap: row.get("iap"),
            hms: row.get("hms"),
            tariff_type: row.get("tariff_type"),
            packing_type: row.get("packing_type"),
            order_app: row.get("order_app"),
            denpend_gms: row.get("denpend_gms"),
            denpend_hms: row.get("denpend_hms"),
            force_update: row.get("force_update"),
            img_tag: row.get("img_tag"),
            is_pay: row.get("is_pay"),
            is_disciplined: row.get("is_disciplined"),
            is_shelves: row.get("is_shelves"),
            submit_type: row.get("submit_type"),
            delete_archive: row.get("delete_archive"),
            charging: row.get("charging"),
            button_grey: row.get("button_grey"),
            app_gift: row.get("app_gift"),
            free_days: row.get("free_days"),
            pay_install_type: row.get("pay_install_type"),
            created_at: row.get("created_at"),
            listed_at: row.get("listed_at"),
            comment: row.get("comment"),
            release_countries: row.get("release_countries"),
            main_device_codes: row.get("main_device_codes"),
        }
    }

    pub fn read_app_metric_from_row(row: &PgRow) -> AppMetric {
        AppMetric {
            id: row.try_get("id").unwrap_or(0),
            app_id: row.get("app_id"),
            version: row.get("version"),
            version_code: row.get("version_code"),
            size_bytes: row.get("size_bytes"),
            sha256: row.get("sha256"),
            info_score: row.get("info_score"),
            info_rate_count: row.get("info_rate_count"),
            download_count: row.get("download_count"),
            price: row.get("price"),
            release_date: row.get("release_date"),
            new_features: row.get("new_features"),
            upgrade_msg: row.get("upgrade_msg"),
            target_sdk: row.get("target_sdk"),
            minsdk: row.get("minsdk"),
            compile_sdk_version: row.get("compile_sdk_version"),
            min_hmos_api_level: row.get("min_hmos_api_level"),
            api_release_type: row.get("api_release_type"),
            created_at: row.get("metrics_created_at"),
        }
    }

    pub fn read_app_rating_from_row(row: &PgRow) -> Option<AppRating> {
        Some(AppRating {
            id: row.try_get("id").unwrap_or(0),
            app_id: row.try_get("app_id").ok()?,
            pkg_name: row.try_get("pkg_name").ok()?,
            average_rating: row.try_get("average_rating").ok()?,
            star_1_rating_count: row.try_get("star_1_rating_count").ok()?,
            star_2_rating_count: row.try_get("star_2_rating_count").ok()?,
            star_3_rating_count: row.try_get("star_3_rating_count").ok()?,
            star_4_rating_count: row.try_get("star_4_rating_count").ok()?,
            star_5_rating_count: row.try_get("star_5_rating_count").ok()?,
            my_star_rating: row.try_get("my_star_rating").ok()?,
            total_star_rating_count: row.try_get("total_star_rating_count").ok()?,
            only_star_count: row.try_get("only_star_count").ok()?,
            full_average_rating: row.try_get("full_average_rating").ok()?,
            source_type: row.try_get("source_type").ok()?,
            created_at: row.try_get("rating_created_at").ok()?,
        })
    }
}

impl<'r> FromRow<'r, PgRow> for FullAppInfo {
    fn from_row(row: &'r PgRow) -> Result<Self, sqlx::Error> {
        Ok(FullAppInfo {
            app_id: row.try_get("app_id")?,
            alliance_app_id: row.try_get("alliance_app_id")?,
            name: row.try_get("name")?,
            pkg_name: row.try_get("pkg_name")?,
            dev_id: row.try_get("dev_id")?,
            developer_name: row.try_get("developer_name")?,
            dev_en_name: row.try_get("dev_en_name")?,
            supplier: row.try_get("supplier")?,
            kind_id: row.try_get("kind_id")?,
            kind_name: row.try_get("kind_name")?,
            tag_name: row.try_get("tag_name")?,
            kind_type_id: row.try_get("kind_type_id")?,
            kind_type_name: row.try_get("kind_type_name")?,
            icon_url: row.try_get("icon_url")?,
            brief_desc: row.try_get("brief_desc")?,
            description: row.try_get("description")?,
            privacy_url: row.try_get("privacy_url")?,
            ctype: row.try_get("ctype")?,
            detail_id: row.try_get("detail_id")?,
            app_level: row.try_get("app_level")?,
            jocat_id: row.try_get("jocat_id")?,
            iap: row.try_get("iap")?,
            hms: row.try_get("hms")?,
            tariff_type: row.try_get("tariff_type")?,
            packing_type: row.try_get("packing_type")?,
            order_app: row.try_get("order_app")?,
            denpend_gms: row.try_get("denpend_gms")?,
            denpend_hms: row.try_get("denpend_hms")?,
            force_update: row.try_get("force_update")?,
            img_tag: row.try_get("img_tag")?,
            is_pay: row.try_get("is_pay")?,
            is_disciplined: row.try_get("is_disciplined")?,
            is_shelves: row.try_get("is_shelves")?,
            submit_type: row.try_get("submit_type")?,
            delete_archive: row.try_get("delete_archive")?,
            charging: row.try_get("charging")?,
            button_grey: row.try_get("button_grey")?,
            app_gift: row.try_get("app_gift")?,
            free_days: row.try_get("free_days")?,
            pay_install_type: row.try_get("pay_install_type")?,
            created_at: row.try_get("created_at")?,
            listed_at: row.try_get("listed_at")?,
            comment: row.try_get("comment")?,
            release_countries: row.try_get("release_countries")?,
            main_device_codes: row.try_get("main_device_codes")?,
            version: row.try_get("version")?,
            version_code: row.try_get("version_code")?,
            size_bytes: row.try_get("size_bytes")?,
            sha256: row.try_get("sha256")?,
            info_score: row.try_get("info_score")?,
            info_rate_count: row.try_get("info_rate_count")?,
            download_count: row.try_get("download_count")?,
            price: row.try_get("price")?,
            release_date: row.try_get("release_date")?,
            new_features: row.try_get("new_features")?,
            upgrade_msg: row.try_get("upgrade_msg")?,
            target_sdk: row.try_get("target_sdk")?,
            minsdk: row.try_get("minsdk")?,
            compile_sdk_version: row.try_get("compile_sdk_version")?,
            min_hmos_api_level: row.try_get("min_hmos_api_level")?,
            api_release_type: row.try_get("api_release_type")?,
            metrics_created_at: row.try_get("metrics_created_at")?,
            average_rating: row.try_get("average_rating")?,
            star_1_rating_count: row.try_get("star_1_rating_count")?,
            star_2_rating_count: row.try_get("star_2_rating_count")?,
            star_3_rating_count: row.try_get("star_3_rating_count")?,
            star_4_rating_count: row.try_get("star_4_rating_count")?,
            star_5_rating_count: row.try_get("star_5_rating_count")?,
            my_star_rating: row.try_get("my_star_rating")?,
            total_star_rating_count: row.try_get("total_star_rating_count")?,
            only_star_count: row.try_get("only_star_count")?,
            full_average_rating: row.try_get("full_average_rating")?,
            source_type: row.try_get("source_type")?,
            rating_created_at: row.try_get("rating_created_at")?,
            title: row.try_get("title").ok(),
            app_recordal_info: row.try_get("app_recordal_info").ok(),
            recordal_entity_title: row.try_get("recordal_entity_title").ok(),
            recordal_entity_name: row.try_get("recordal_entity_name").ok(),
            updated_at: row.try_get("updated_at").unwrap_or_else(|_| Local::now()),
        })
    }
}
